.common: &common
  script:
  - npm install && npm test --ignore-scripts=false && npm run build --ignore-scripts=false

node:14:
  <<: *common
  image: node:14

node:16:
  <<: *common
  image: node:16

node:17:
  <<: *common
  image: node:17
